### ISSUE TITLE
Provided examples in README doesn't work

### ISSUE THREAD

**Issue by gudleik** [Skalar/pronto-image-classifer#4]
Followed the steps from the README to build, run and test:

```
$ docker build -t pronto-image-classifer . --platform linux/amd64
$ docker run --name tf1 --platform linux/amd64 --publish 5000:5000 --rm pronto-image-classifer
```

Testing single image:
```
$ curl -G -d img=https://prod-5929f14.s3.eu-north-1.amazonaws.com/accounts/136/files/ck5du6wwc006c07qx9j596su9 localhost:5000/api/predict

invalid parameters:https://prod-5929f14.s3.eu-north-1.amazonaws.com/accounts/136/files/ck5du6wwc006c07qx9j596su9 EX:[Errno 2] No such file or directory: 'fls/qx9j596su9.png'
```

Testing multiple images:

```
$ curl -i -X POST -H "Content-Type: application/json" -d "{\"imgs\":[\"https://prod-c467854.s3.eu-north-1.amazonaws.com/accounts/128/files/3oXVxlCDCDjxnh9sPYA7g\",\"https://prod-5929f14.s3.eu-north-1.amazonaws.com/accounts/136/files/ck57u3urw001d07hd6lbe2ciz\"]}" localhost:5000/api/predict
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 250
Server: Werkzeug/2.0.1 Python/3.8.11
Date: Fri, 30 Jul 2021 09:31:12 GMT

invalid parameters: {'imgs': ['https://prod-c467854.s3.eu-north-1.amazonaws.com/accounts/128/files/3oXVxlCDCDjxnh9sPYA7g', 'https://prod-5929f14.s3.eu-north-1.amazonaws.com/accounts/136/files/ck57u3urw001d07hd6lbe2ciz']} EX:name 'time' is not defined
```

**Comment by joshclement0** [comment]
These should work now. Also there should be a little better error handling now (if it does fail it won't fail with a 200)

**Comment by gudleik** [comment]
Nice, the single tests works. But the test multiple command returns error:

```
ERROR:app:Exception on /api/predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 586, in get_json
    rv = self.json_module.loads(data)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 216, in loads
    return _json.loads(s, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 86, in pred_imgs
    form = request.get_json()
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 595, in get_json
    rv = self.on_json_loading_failed(e)
  File "/usr/local/lib/python3.8/site-packages/flask/wrappers.py", line 131, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 89, in pred_imgs
    return "invalid parameters: {} EX:{}".format(form,e),400
UnboundLocalError: local variable 'form' referenced before assignment
```
